docker run -v /path/to/data/on/your/machine:/data wipp/mist:2.0.7 --imageDir=/data/inputs --filenamePatternType=ROWCOL --filenamePattern="img_r{rrr}_c{ccc}.ome.tif" --gridOrigin=UL --gridWidth=5 --gridHeight=5 --startTileRow=1 --startTileCol=1 --startRow=0 --startCol=0 --extentWidth=5 --extentHeight=5 --isTimeSlices=false --assembleNoOverlap=false --stageRepeatability=0 --overlapUncertainty=5 --programType=java --outputPath=/data/outputs




container:
  args:
    - '--imageDir'
    - '{{inputs.parameters.imageDir}}'
    - '--filenamePatternType'
    - '{{inputs.parameters.filenamePatternType}}'
    - '--filenamePattern'
    - '{{inputs.parameters.filenamePattern}}'
    - '--gridOrigin'
    - '{{inputs.parameters.gridOrigin}}'
    - '--gridWidth'
    - '{{inputs.parameters.gridWidth}}'
    - '--gridHeight'
    - '{{inputs.parameters.gridHeight}}'
    - '--startTileRow'
    - '{{inputs.parameters.startTileRow}}'
    - '--startTileCol'
    - '{{inputs.parameters.startTileCol}}'
    - '--startRow'
    - '{{inputs.parameters.startRow}}'
    - '--startCol'
    - '{{inputs.parameters.startCol}}'
    - '--extentWidth'
    - '{{inputs.parameters.extentWidth}}'
    - '--extentHeight'
    - '{{inputs.parameters.extentHeight}}'
    - '--isTimeSlices'
    - '{{inputs.parameters.isTimeSlices}}'
    - '--assembleNoOverlap'
    - '{{inputs.parameters.assembleNoOverlap}}'
    - '--stageRepeatability'
    - '{{inputs.parameters.stageRepeatability}}'
    - '--overlapUncertainty'
    - '{{inputs.parameters.overlapUncertainty}}'
    - '--programType'
    - '{{inputs.parameters.programType}}'
    - '--outputPath'
    - '{{inputs.parameters.outputPath}}'
  image: 'wipp/mist:2.0.7'
